---

apiVersion: "v2"
type: "application"
name: "notifications-api"
description: "A Helm chart for the Univention Portal Notifications API"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

# Portal Version
appVersion: "1.16.0"

dependencies:
  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.2.0"
  - name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "^12.2.1"
    condition: "postgresql.bundled"

...
