---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Dummy values for running the Helm linter on the notifications-api.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .


notificationsApi:
  applyDatabaseMigrations: "True"
  devMode: "True"
  environment: "staging"
  logLevel: "DEBUG"
  apiPrefix: "/univention/portal/notifications-api"

probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

postgresql:
  connection:
    host: "postgresql-host"
    port: "postgresql-port"
  auth:
    password: "stub-password"

ingress:
  host: "stub-host"
  tls:
    enabled: true
    secretName: "stub-tls-secret"
