---

# Dummy values for running the Helm linter on the notifications-api.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .


## Application-specific
notificationsapi:
  apply_database_migrations: "True"
  dev_mode: "True"
  environment: "staging"
  log_level: "DEBUG"
  api_prefix: "/univention/portal/notifications-api"


## Kubernetes ingress
ingress:
  enabled: false
  host: "portal.example.develop.souvap-univention.de"


## Istio based
istio:
  enabled: true
  host: "portal.example.develop.souvap-univention.de"


## Docker image
image:
  tag: "branch-feature-example"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false


## PostgreSQL configuration
postgresql:
  bundled: true
  # You have to define the connection if you are not using the bundled postgresql.
  # connection:
  #   host:
  #   port:

...
