---
# Default values for univention-notifications-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


# -- Application configuration of the Notifcations API
notificationsApi:
  # -- Apply database migrations automatically
  applyDatabaseMigrations: "True"
  # -- Activate the development mode. Do not use this in production deployments.
  devMode: "False"
  # -- TODO: Clarify usage of this parameter
  environment: "production"
  # -- Log level configuration. E.g. "DEBUG", "INFO", "WARNING", "ERROR".
  logLevel: "WARNING"
  # -- SQL command logging, e.g. "True" or "False"
  sqlEcho: "False"
  # -- The URL prefix under which the API shall be deployed.
  apiPrefix: "/univention/portal/notifications-api/"


## Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: true
  ingressClassName: "nginx"
  annotations:
    # Ingress-Nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/univention/portal/notifications-api(/.*)$ $1 break;
    # Nginx
    nginx.org/location-snippets: |
      rewrite ^/univention/portal/notifications-api(/.*)$ $1 break;
    nginx.org/mergeable-ingress-type: "minion"
    # HAProxy
    haproxy.org/path-rewrite: ^/univention/portal/notifications-api(/.*)$ \1
    # HAProxy - Community: https://haproxy-ingress.github.io/
    haproxy-ingress.github.io/rewrite-target: /
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  paths:
    - pathType: "Prefix"
      path: "/univention/portal/notifications-api/"
  tls:
    enabled: true
    secretName: ""


## Istio support
istio:
  # -- Set this to `true` in order to enable the installation on Istio related objects.
  enabled: false
  # -- The hostname. This parameter has to be supplied. Example `portal.example`.
  host: null
  virtualService:
    enabled: true
    annotations:
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


## Docker image
image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/univention-portal/notifications-api"
  imagePullPolicy: "Always"
  tag: "latest"

  ## Define image sha256 as an alternative to `tag`
  # sha256:


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


## Deployment resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "4Gi"
    cpu: "4"

## Kubernetes Service
service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 8080
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800


# -- PostgreSQL settings.
#
# The bitnami helm chart does contain all details of what can be configured:
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  # -- Set to `true` if you want PostgreSQL to be installed as well.
  bundled: true
  # -- Connection parameters. These are required if you use an external database.
  connection:
    host:
    port:
  auth:
    username: "notifications"
    database: "notifications"
    password: "easyPassword"
    postgresPassword: "postgres"

...
