# The test environment gives developers an easy way to run unit and ui tests:
#
#   docker compose run --build test
#   docker compose run --build test yarn test:e2e:headless --browser chrome
#

ARG DOCKER_PROXY=""

FROM ${DOCKER_PROXY}cypress/browsers:node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1@sha256:5233c463749ef725afc4b15ad99caae27603282c501646b7267b0e071d128974 AS test

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .

RUN \
  yarn install --frozen-lockfile \
  && yarn cache clean

COPY . .

CMD ["yarn", "test:unit"]
