version: '3.0'

services:
  test:
    profiles:
      - test
    build:
      context: .
      target: test
    container_name: portal-frontend-test
    # Not mounting the source code since this would overwrite the node_modules folder
