# The test environment gives developers an easy way to run unit and ui tests:
#
#   docker compose run --build test
#   docker compose run --build test yarn test:e2e:headless --browser chrome
#

ARG DOCKER_PROXY=""

FROM ${DOCKER_PROXY}cypress/browsers:node-24.15.0-chrome-147.0.7727.137-1-ff-150.0.1-edge-147.0.3912.86-1@sha256:014fcde81d227125c9ffb66fc06721229795542237c349e710f6dafe5413ee86 AS test

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .

RUN \
  yarn install --frozen-lockfile \
  && yarn cache clean

COPY . .

CMD ["yarn", "test:unit"]
