# The test environment gives developers an easy way to run unit and ui tests:
#
#   docker compose run --build test
#   docker compose run --build test yarn test:e2e:headless --browser chrome
#
FROM ${DOCKER_PROXY}cypress/browsers:node14.17.6-chrome100-ff98@sha256:3f1ceb98712c697071ac194a0cae263a8b082af8ed418b7792dd9b0888a0338f AS test

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .

RUN \
  yarn install --frozen-lockfile \
  && yarn cache clean

COPY . .

CMD ["yarn", "test:unit"]
