---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

version: '3.0'

services:

  reverse-proxy:
    build:
      context: ../docker/reverse-proxy
    container_name: portal-frontend-reverse-proxy
    ports:
      - "7777:8080"
    environment:
      PORTAL_FRONTEND_BASE_URL: "http://host.docker.internal:8080"
      NUBUS_BASE_URL: "https://portal.uv-tkintscher.opendesk.site"

  # A container which does provide only the environment needed for development.
  #
  # This is intended for use cases when you either want to be sure that nothing
  # from your local machine interferes with your development or when you are on
  # a non-Linux operating system and you want to run this in a well defined
  # Linux environment to avoid issues from subtle differences.
  dev:
    profiles:
      - dev
    build:
      context: .
      target: local-dev-env
    container_name: portal-frontend-dev-env
    environment:
      YARN_CACHE_FOLDER: /root/.cache/yarn
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - portal-frontend-dev-env-dotcache:/root/.cache
      - portal-frontend-dev-env-node-modules:/app/node_modules

  test:
    profiles:
      - test
    build:
      context: .
      target: test
      dockerfile: Dockerfile.test
    container_name: portal-frontend-test

volumes:
  portal-frontend-dev-env-dotcache:
  portal-frontend-dev-env-node-modules:

...
