# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'

include:
  - project: univention/customers/dataport/upx/common-ci
    ref: "v1.14.0"
    file:
      - "defaults/stages.yaml"
      - "templates/kaniko.yaml"
      - "templates/souvap.yaml"
      - "scripts/bash-header.yaml"

# TODO: for keeping it simple, this is a duplicate to the one in the frontend pipeline
#       but since the debian build is to go away eventually, this is probably acceptable
build-debian-package-builder-1:
  stage: "prepare"
  extends: ".kaniko"
  needs: []
  variables:
    IMAGE_NAME: "deb-builder"

build-debian-package:
  stage: "package"
  needs:
    - job: "build-debian-package-builder-1"
  image: "$BUILD_IMAGE_TAG"
  before_script:
    - |
      apt-get -qq update
      apt-get -q --assume-yes build-dep .
  script:
    - |
      source ~/.nvm/nvm.sh
      dpkg-buildpackage --no-sign
      rm -fr public
      mkdir public
      mv -v ../*.{deb,dsc,tar.gz,buildinfo,changes} public/
  artifacts:
    paths:
      - "public/"
    expire_in: "1 week"

...
