---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "check-added-large-files"
        name: "check for added large files"
      - id: "check-ast"
        name: "check python ast"
      - id: "check-case-conflict"
        name: "check for case conflicts"
      - id: "check-docstring-first"
        name: "check docstring is first"
      - id: "check-executables-have-shebangs"
        name: "check that executables have shebangs"
      - id: "check-json"
        name: "check json"
      - id: "check-merge-conflict"
        name: "check for merge conflicts"
      - id: "check-yaml"
        name: "check yaml"
        args:
          - "--allow-multiple-documents"
          # Allow custom tags like Gitlab's "!reference" tag.
          - "--unsafe"
        exclude: '^helm/.+/templates/'
      - id: "check-json"
        exclude: 'conffiles/.*[.]json$'
      - id: "pretty-format-json"
        exclude: 'conffiles/.*[.]json$'
        args:
          - "--autofix"
          - "--no-ensure-ascii"
      - id: "check-symlinks"
        name: "check for broken symlinks"
      - id: "detect-private-key"
        name: "detect private key"
      - id: "end-of-file-fixer"
        name: "fix end of files"
        exclude: '^helm/.+/README.md$'
      - id: "fix-byte-order-marker"
        name: "fix utf-8 byte order marker"
      - id: "trailing-whitespace"
        name: "trim trailing whitespace"

  # "Python blocks in UCR config templates"
  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-ucr"
    rev: "0.0.10"
    hooks:
      - id: "ucr-flake8"
      - id: "ucr-autopep8"
      - id: "ucr-ruff-fix"

  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-debian.git"
    rev: "v1.1.0"
    hooks:
      - id: "debian-control"

  - repo: "https://github.com/compilerla/conventional-pre-commit"
    rev: "v3.0.0"
    hooks:
      - id: "conventional-pre-commit"
        name: "Conventional Commit"
        stages: ["commit-msg"]

  - repo: "https://git.knut.univention.de/univention/dist/pre-commit-hooks/addlicense"
    rev: "v1.0.1"
    hooks:
      - id: "addlicense"
        name: "Check or add license headers to files"

  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.33.0"
    hooks:
      - id: "yamllint"
        name: "yamllint"
        args:
          - "--config-file=.yamllint"
          - "--format=parsable"
          - "--strict"

  - repo: "https://github.com/google/yapf"
    rev: "v0.40.2"
    hooks:
      - id: "yapf"
        name: "yapf"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.1.9"
    hooks:
      - id: "ruff"
        name: "ruff"
        args:
          - "--fix"
          - "--show-source"
          - "--exit-non-zero-on-fix"
          - "--extend-select=COM"

  - repo: "https://github.com/hhatto/autopep8"
    rev: "v2.0.4"
    hooks:
      - id: "autopep8"
        name: "autopep8"
        args:
          - "--in-place"
          - "--aggressive"
          - "--aggressive"
          - "--experimental"

  - repo: "https://github.com/PyCQA/flake8"
    rev: "6.1.0"
    hooks:
      - id: "flake8"
        name: "flake8"

  - repo: "https://github.com/pylint-dev/pylint"
    rev: "v3.0.3"
    hooks:
      - id: "pylint"
        name: "pylint"
        additional_dependencies:
          - "pytest"

  - repo: "https://github.com/hadolint/hadolint"
    rev: "v2.12.0"
    hooks:
      - id: "hadolint"
        name: "Lint Dockerfiles"
        types: ["dockerfile"]
        args:
          - "--no-color"
          - "--strict-labels"

  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-compose-check"
    rev: "7702a8801a158b8595569dd29e2dd655d8a08310"
    hooks:
      - id: "docker-compose-check"
        name: "Validate docker-compose files (python)"

  # Cloned from github.com/IamTheFij/docker-pre-commit
  - repo: "https://gitlab.com/univention/pre-commit-hooks/docker-pre-commit"
    rev: "v3.0.1"
    hooks:
      - id: "docker-compose-check"
        name: "Validate docker compose files (bash)"

  - repo: "https://gitlab.com/univention/pre-commit-hooks/pre-commit-shell"
    rev: "v1.0.6+uv1"
    hooks:
      - id: "shell-lint"
        name: "Shell Syntax Check"
        args:
          - "--enable=all"
          - "--external-sources"

  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: "v0.1.23"
    hooks:
      - id: "shellcheck"
        name: "Shellcheck Bash Linter"
        args:
          - "--enable=all"
      - id: "helmlint"
        name: "helmlint"

  - repo: "https://github.com/norwoodj/helm-docs"
    rev: "v1.12.0"
    hooks:
      - id: "helm-docs"
        name: "Helm Docs"
        args:
          - "--chart-search-root=helm"
          - "--template-files=README.md.gotmpl"
        always_run: true

  # Uses `GITLAB_SERVER`, `GITLAB_PROJECT_ID` and `GITLAB_PRIVATE_TOKEN`
  - repo: "https://gitlab.com/univention/pre-commit-hooks/gitlab-ci-linter"
    rev: "v1.0.6+uv2"
    hooks:
      - id: "gitlab-ci-linter"
        name: ".gitlab-ci.yml linter"
        stages:
          - "manual"

...
