version: '3.3'

services:
  portal-server: 
    build:
      context: .
      dockerfile: images/portal-server/Dockerfile
    volumes:
      - type: bind
        source: /usr/lib/univention-portal/config
        target: /usr/lib/univention-portal/config
  apache:
    build:
      context: .
      dockerfile: images/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /etc/apache2/sites-available/univention-portal.conf
        target: /etc/apache2/sites-available/univention-portal.conf