version: '3.9'

services:
  portal-backend:
    build:
      target: dev
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./portal-backend:/portal-backend
      - ./portal-frontend:/portal-frontend
    ports:
      - "127.0.0.1:${PORTAL_PORT:-8080}:80"
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]

  notifications-api:
    build:
      target: dev
    environment:
      DATABASE_URL: sqlite:////db/db.sqlite
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./notifications-api:/notifications-api
      - ./db:/db
    ports:
      - "127.0.0.1:${NOTIFICATIONS_API_PORT:-8081}:80"
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]

  mercure-hub:
    environment:
      MERCURE_PUBLISHER_JWT_KEY:
      MERCURE_SUBSCRIBER_JWT_KEY:
    ports:
      - "127.0.0.1:${MERCURE_HUB_PORT:-8082}:80"
    command: ["caddy", "run", "-config", "/etc/caddy/Caddyfile.dev"]

  keycloak:
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:${KEYCLOAK_PORT:-8083}:8080"
    command: ["start-dev"]

  docs:
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./docs/docs:/docs
      - ./:/mnt
    ports:
      - "127.0.0.1:${DOCS_PORT:-8084}:8000"
