site_name: UCS Portal Notes
docs_dir: docs
theme:
  name: material
  # palette:
  #   scheme: slate
  #   primary: blue gray
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search:
  - mkdocstrings:
  - awesome-pages:
  - macros:
  - mermaid2:
      arguments:
        theme: 'dark'
