#!/bin/bash
#
# Univention Portal
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2019-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only
. /usr/lib/univention-server/lib/server_password_change/debug.sh

if [ "$1" = "postchange" ]; then
	systemctl reload-or-try-restart univention-portal-server.service
fi

exit 0
