sonar.projectKey=univention_dev_projects_portal_45beedd0-ae8e-4068-9bfe-301c68adfcdd
sonar.qualitygate.wait=true
sonar.links.homepage=https://git.knut.univention.de/univention/dev/projects/portal
sonar.links.issue=https://git.knut.univention.de/univention/dev/internal/team-nubus/-/issues
sonar.links.scm=https://git.knut.univention.de/univention/dev/projects/portal
