#!/usr/bin/python3
#
# Univention Portal
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# SPDX-FileCopyrightText: 2020-2025 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

import click

from univention.portal.cli import (
    add as _add,
    add_default as _add_default,
    add_selfservice_default as _add_selfservice_default,
    add_umc_default as _add_umc_default,
    list_extensions as _list_extensions,
    list_portals as _list_portals,
    pull as _pull,
    push as _push,
    remove as _remove,
    update as _update,
)
from univention.portal.log import get_logger, setup_logger


logger = get_logger("cli")


@click.group()
@click.option("--log-stream/--dont-log-stream", default=False)
def cli(log_stream: bool):
    setup_logger(stream=log_stream)


@cli.command("add-default")
@click.option("--update/--dont-update", default=False)
def add_default(update: bool):
    _add_default(update)


@cli.command("add-umc-default")
@click.option("--update/--dont-update", default=False)
def add_umc_default(update: bool):
    _add_umc_default(update)


@cli.command("add-selfservice-default")
@click.option("--update/--dont-update", default=False)
def add_selfservice_default(update: bool):
    _add_selfservice_default(update)


@cli.command()
@click.argument("name")
@click.option("--update/--dont-update", default=True)
def add(name: str, update: bool):
    _add(name, update)


@cli.command()
@click.argument("name")
@click.option("--purge", default=False)
def remove(name: str, purge: bool):
    _remove(name, purge)


@cli.command("list")
def list_portals():
    _list_portals()


@cli.command()
@click.argument("name")
def push(name: str):
    _push(name)


@cli.command()
@click.argument("name")
def pull(name: str):
    _pull(name)


@cli.command()
@click.argument("names", nargs=-1)
@click.option("--reason", default="force")
def update(names: str, reason: str):
    _update(names, reason)


@cli.command("list-extensions")
def list_extensions():
    _list_extensions()


if __name__ == "__main__":
    cli()
