#!/usr/bin/python3
#
# Univention Portal
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# Copyright 2020-2024 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

import click

from univention.portal.cli import (
    add as _add,
    add_default as _add_default,
    add_selfservice_default as _add_selfservice_default,
    add_umc_default as _add_umc_default,
    list_extensions as _list_extensions,
    list_portals as _list_portals,
    pull as _pull,
    push as _push,
    remove as _remove,
    update as _update,
)
from univention.portal.log import get_logger, setup_logger


logger = get_logger("cli")


@click.group()
@click.option("--log-stream/--dont-log-stream", default=False)
def cli(log_stream: bool):
    setup_logger(stream=log_stream)


@cli.command("add-default")
@click.option("--update/--dont-update", default=False)
def add_default(update: bool):
    _add_default(update)


@cli.command("add-umc-default")
@click.option("--update/--dont-update", default=False)
def add_umc_default(update: bool):
    _add_umc_default(update)


@cli.command("add-selfservice-default")
@click.option("--update/--dont-update", default=False)
def add_selfservice_default(update: bool):
    _add_selfservice_default(update)


@cli.command()
@click.argument("name")
@click.option("--update/--dont-update", default=True)
def add(name: str, update: bool):
    _add(name, update)


@cli.command()
@click.argument("name")
@click.option("--purge", default=False)
def remove(name: str, purge: bool):
    _remove(name, purge)


@cli.command("list")
def list_portals():
    _list_portals()


@cli.command()
@click.argument("name")
def push(name: str):
    _push(name)


@cli.command()
@click.argument("name")
def pull(name: str):
    _pull(name)


@cli.command()
@click.argument("names", nargs=-1)
@click.option("--reason", default="force")
def update(names: str, reason: str):
    _update(names, reason)


@cli.command("list-extensions")
def list_extensions():
    _list_extensions()


if __name__ == "__main__":
    cli()
