import MyForm from '../../src/components/forms/Form.vue';

export default {
  title: 'Widgets/Tree',
  component: MyForm,
};

const Template = (args) => ({
  components: { MyForm },
  setup() {
    return { args };
  },
  template: '<my-form v-model="args.modelValue" :widgets="args.widgets"></my-form>',
});

const tree = [{
  id: 'cn=univention,dc=demo,dc=univention,dc=de',
  label: 'univention',
  icon: 'udm-settings-cn',
  path: 'demo.univention.de:/univention',
  objectType: 'settings/cn',
  $operations$: ['search'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: true,
}, {
  id: 'cn=dns,dc=demo,dc=univention,dc=de',
  label: 'dns',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/dns',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=dhcp,dc=demo,dc=univention,dc=de',
  label: 'dhcp',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/dhcp',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=mail,dc=demo,dc=univention,dc=de',
  label: 'mail',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/mail',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=samba,dc=demo,dc=univention,dc=de',
  label: 'samba',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/samba',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=users,dc=demo,dc=univention,dc=de',
  label: 'users',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/users',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=groups,dc=demo,dc=univention,dc=de',
  label: 'groups',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/groups',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=nagios,dc=demo,dc=univention,dc=de',
  label: 'nagios',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/nagios',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=shares,dc=demo,dc=univention,dc=de',
  label: 'shares',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/shares',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=kerberos,dc=demo,dc=univention,dc=de',
  label: 'kerberos',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/kerberos',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=networks,dc=demo,dc=univention,dc=de',
  label: 'networks',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/networks',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=policies,dc=demo,dc=univention,dc=de',
  label: 'policies',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/policies',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=printers,dc=demo,dc=univention,dc=de',
  label: 'printers',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/printers',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=computers,dc=demo,dc=univention,dc=de',
  label: 'computers',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/computers',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'cn=monitoring,dc=demo,dc=univention,dc=de',
  label: 'monitoring',
  icon: 'udm-container-cn',
  path: 'demo.univention.de:/monitoring',
  objectType: 'container/cn',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'ou=People,dc=demo,dc=univention,dc=de',
  label: 'People',
  icon: 'udm-container-ou',
  path: 'demo.univention.de:/People',
  objectType: 'container/ou',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}, {
  id: 'ou=Departments,dc=demo,dc=univention,dc=de',
  label: 'Departments',
  icon: 'udm-container-ou',
  path: 'demo.univention.de:/Departments',
  objectType: 'container/ou',
  $operations$: ['add', 'edit', 'remove', 'search', 'move', 'subtree_move'],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
}];
const rootNode = {
  id: 'dc=demo,dc=univention,dc=de',
  label: 'demo.univention.de:/',
  icon: 'udm-container-dc',
  path: 'demo.univention.de:/',
  objectType: 'container/dc',
  $operations$: [
    'search',
    'edit',
  ],
  $flags$: [],
  $childs$: true,
  $isSuperordinate$: false,
};

export const Default: any = Template.bind({});
Default.args = {
  modelValue: { tree: '' },
  widgets: [
    {
      type: 'Tree',
      name: 'tree',
      label: 'Tree',
      lists: tree,
      rootNode,
    },
  ],
};
