# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "{{ include "common.names.fullname" . }}-branding"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
binaryData:
  custom.css: "{{- include "portalFrontend.branding.css" . }}"
  favicon.ico: "{{- include "portalFrontend.branding.favicon" . }}"
  logo.svg: "{{- include "portalFrontend.branding.logo" . }}"
  portal_background_image.svg: "{{- include "portalFrontend.branding.backgroundImage" . }}"

...
