# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

{{ include "common.configMap" (dict "top" . "overrides" "portal-frontend.configMap") }}

{{- define "portal-frontend.configMap" }}
{{- with .top }}
data:
  ENVIRONMENT: "{{ .Values.portalFrontend.environment }}"
  LOG_LEVEL: "{{ .Values.portalFrontend.logLevel }}"
{{- end }}
{{- end }}
...
