---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: '{{ include "common.names.fullname" . }}'
data:
  ENVIRONMENT: "{{ .Values.portalFrontend.environment }}"
  LOG_LEVEL: "{{ .Values.portalFrontend.logLevel }}"

...
