# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: "{{ include "common.names.fullname" . }}"
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/branding-configmap: {{ include (print .Template.BasePath "/branding-configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" .) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets  }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: "portal-frontend"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          env:
          {{- with .Values.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: "{{ include "common.names.fullname" . }}"
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.livenessProbe "context" .) | nindent 12 }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.readinessProbe "context" .) | nindent 12 }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.startupProbe "context" .) | nindent 12 }}
          ports:
            {{- range $key, $value := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- if .Values.resources }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" .) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: var-run-volume
              mountPath: /var/run
            - name: var-lib-nginx-volume
              mountPath: /var/lib/nginx
            - name: {{ printf "%s-nginx" (include "common.names.fullname" .) | quote }}
              subPath: nginx.conf
              mountPath: /etc/nginx/nginx.conf
            {{- if .Values.portalFrontend.branding.favicon }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/favicon/favicon.ico"
              subPath: "favicon.ico"
            {{- end }}
            {{- if .Values.portalFrontend.branding.faviconSvg }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/favicon/favicon.svg"
              subPath: "favicon.svg"
            {{- end }}
            {{- if .Values.portalFrontend.branding.favicon96Png }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/favicon/favicon-96x96.png"
              subPath: "favicon-96x96.png"
            {{- end }}
            {{- if .Values.portalFrontend.branding.appleTouchIcon }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/favicon/apple-touch-icon.png"
              subPath: "apple-touch-icon.png"
            {{- end }}
            {{- if .Values.portalFrontend.branding.webManifestIcon192 }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/favicon/web-app-manifest-192x192.png"
              subPath: "web-app-manifest-192x192.png"
            {{- end }}
            {{- if .Values.portalFrontend.branding.webManifestIcon512 }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/favicon/web-app-manifest-512x512.png"
              subPath: "web-app-manifest-512x512.png"
            {{- end }}
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/css/custom.css"
              subPath: "custom.css"
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/icons/logo.svg"
              subPath: "logo.svg"
            - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
              mountPath: "/var/www/html/custom/portal_background_image.svg"
              subPath: "portal_background_image.svg"
            {{- if eq .Values.assetLoader.backend "ldap" }}
            - name: portal-assets-volume
              mountPath: /var/www/html/univention/portal
              readOnly: true
            {{- else }}
            - name: portal-assets-volume
              mountPath: /var/www/html/univention/portal
              subPath: "portal-assets"
              readOnly: true
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
        - name: "asset-loader"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.assetLoader.image.registry .Values.global.imageRegistry }}/{{ .Values.assetLoader.image.repository }}:{{ .Values.assetLoader.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.assetLoader.image.pullPolicy .Values.global.imagePullPolicy | quote }}
          {{- if eq .Values.assetLoader.backend "ldap" }}
          args: ["loader_ldap.py"]
          env:
            - name: LDAP_URI
              value: {{ required "The parameter \"ldap.connection.uri\" is required when using ldap backend." .Values.ldap.connection.uri | quote }}
            - name: LDAP_BIND_DN
              value: {{ required "The parameter \"ldap.connection.bindDn\" is required when using ldap backend." .Values.ldap.connection.bindDn | quote }}
            - name: LDAP_BIND_PW
              value: {{ required "The parameter \"ldap.connection.bindPassword\" is required when using ldap backend." .Values.ldap.connection.bindPassword | quote }}
            - name: LDAP_BASE_DN
              value: {{ required "The parameter \"ldap.connection.baseDn\" is required when using ldap backend." .Values.ldap.connection.baseDn | quote }}
            - name: UDM_API_URL
              value: {{ required "The parameter \"ldap.udm.url\" is required when using ldap backend." .Values.ldap.udm.url | quote }}
            - name: UDM_API_USER
              value: {{ required "The parameter \"ldap.udm.user\" is required when using ldap backend." .Values.ldap.udm.user | quote }}
            - name: UDM_API_PASSWORD
              value: {{ required "The parameter \"ldap.udm.password\" is required when using ldap backend." .Values.ldap.udm.password | quote }}
            - name: PORTAL_DN
              value: {{ required "The parameter \"ldap.portalDn\" is required when using ldap backend." .Values.ldap.portalDn | quote }}
            - name: POLL_INTERVAL
              value: {{ .Values.ldap.pollInterval | quote }}
            - name: OUTPUT_DIR
              value: "/portal-assets"
          {{- else }}
          args: ["loader.py"]
          env:
            - name: NATS_SERVER
              value: {{ required "The parameter \"nats.connection.url\" is required when using nats backend." .Values.nats.connection.url | quote }}
            - name: NATS_KV_BUCKET
              value: {{ required "The parameter \"nats.bucketName\" is required when using nats backend." .Values.nats.bucketName | quote }}
            - name: NATS_USER
              value: {{ required "The parameter \"nats.auth.user\" is required when using nats backend." .Values.nats.auth.user | quote }}
            - name: NATS_PASSWORD
              value: {{ required "The parameter \"nats.auth.password\" is required when using nats backend." .Values.nats.auth.password | quote }}
            - name: OUTPUT_DIR
              value: "/portal-assets"
          {{- end }}
          {{- if .Values.assetLoader.resources }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.assetLoader.resources "context" .) | nindent 12 }}
          {{- end }}
          {{- if eq .Values.assetLoader.backend "ldap" }}
          readinessProbe:
            exec:
              command:
                - test
                - -f
                - /portal-assets/.ready
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - name: portal-assets-volume
              mountPath: /portal-assets
      volumes:
        - name: "var-run-volume"
          emptyDir: {}
        - name: "var-lib-nginx-volume"
          emptyDir: {}
        - name: {{ printf "%s-nginx" (include "common.names.fullname" .) | quote }}
          configMap:
            name: {{ printf "%s-nginx" (include "common.names.fullname" .) | quote }}
            defaultMode: 420
        - name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
          configMap:
            name: {{ printf "%s-branding" (include "common.names.fullname" .) | quote }}
        - name: "portal-assets-volume"
          emptyDir: {}
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
