# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH
{{- if .Values.ingress.enabled }}
{{- range $index, $ingressConfig := .Values.extraIngresses }}
{{- $_ := set $ingressConfig "host" (default $.Values.ingress.host $ingressConfig.host) }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "common.names.fullname" $) (required "Ingress must have a name. Missing key \"name\" on extraIngress definition." .name) | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end }}
  {{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ .host | quote }}
      secretName: "{{ .tls.secretName }}"
  {{- end }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
          {{- end }}

...
{{- end }}
{{- end }}
