# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

{{- range $key, $val := .Values.extraIngresses }}
---
{{/* The name of the key is needed later to give the Ingress a proper name.
     This does "remember" the value on the ingress dict. */}}
{{- $_ := set $val "_name" $key }}

{{- /* Apply defaults from ".Values.ingress" */}}
{{- $_ := set $val "ingressClassName" (default $.Values.ingress.ingressClassName $val.ingressClassName) }}
{{- $_ := set $val "host" (default $.Values.ingress.host $val.host) }}
{{- $_ := set $val.tls "secretName" (default $.Values.ingress.tls.secretName $val.tls.secretName) }}
{{- if eq $val.tls.enabled nil }}
{{- $_ := set $val.tls "enabled" $.Values.ingress.tls.enabled }}
{{- end }}

{{- include "common.ingress" (dict "top" $ "ingress" $val "overrides" "portal-frontend.extraIngresses") }}
{{- end }}


{{- define "portal-frontend.extraIngresses" }}
metadata:
  name: {{ print (include "common.names.fullname" .top) "-" .ingress._name | quote }}
{{- end }}
