# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

# flake8: noqa

"""empty message

Revision ID: 3d4de5e11556
Revises: e63f346068f6
Create Date: 2023-03-17 08:15:33.190688

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d4de5e11556'
down_revision = 'e63f346068f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'receiveTime')
    op.drop_column('notification', 'readTime')
    op.drop_column('notification', 'confirmationTime')
    op.drop_column('notification', 'data')
    op.drop_column('notification', 'notificationType')
    op.drop_column('notification', 'needsConfirmation')
    op.drop_column('notification', 'sticky')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Adjusted in the following way:
    #
    # - When going backwards all attributes allow "null" values. Since we don't have any
    #   production release out yet, there was no value in implementing a more correct
    #   downgrade operation which would fill all fields with sensible values.

    op.add_column('notification', sa.Column('sticky', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('needsConfirmation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('notificationType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('confirmationTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('readTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('receiveTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
