/* tslint:disable */
/* eslint-disable */
/**
 * Notifications API
 *  The Notifications API is intended to be used so that applications can send notifications so that they are visible within the Univention Portal.  The API endpoints can be grouped as follows:  - *Notification Sender API* -- This subset of endpoints is intended to be used   by applications who want to send a notification for a given user.  - *Notification Client API* -- This subset shall fulfill the needs of the   Univention Portal, so that it can show the notifications to the user.  Note: The groups are not necessarily disjoint. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

