# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.20.0"
    file:
      - "defaults/stages.yaml"
      - "templates/souvap.yaml"
      - "jobs/container-build-souvap.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME: "notifications-api-test-runner"
    KANIKO_ARGS: "--target=test"
  - IMAGE_NAME: "notifications-api"

.publish-matrix: &publish-matrix
  - IMAGE_NAME: "notifications-api"

container-build:
  parallel:
    matrix: *build-matrix
  variables:
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR/notifications-api"

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

test-notifications-api:
  stage: "test"
  image: "$CI_REGISTRY_IMAGE/notifications-api-test-runner:${RELEASE_VERSION}"
  script:
    - |
      cd notifications-api
      pytest --cov=app --cov-report=term --cov-report=xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: "cobertura"
        path: "notifications-api/coverage.xml"

push-image-souvap:
  parallel:
    matrix: *publish-matrix

container-sign-souvap:
  parallel:
    matrix: *publish-matrix

...
