stages:
  - prepare
  - lint
  - build
  - test
  - package
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

# include:
#   - project: univention/dist/docker-services
#     file: kaniko.yml
#   - project: univention/customers/dataport/upx/common-ci
#     file:
#       - templates/souvap.yaml


build-notifications-api-test-runner:
  stage: prepare
  script:
    - echo "build-notifications-api-test-runner running"
  # extends:
  #   - .kaniko
  # needs: []
  # variables:
  #   DOCKERFILE_PATH: "notifications-api/Dockerfile"
  #   CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/notifications-api-test-runner"
  #   KANIKO_ARGS: "--target=test"
  #   KANIKO_BUILD_CONTEXT: "notifications-api"
  # script:
  #   - echo $KANIKO_BUILD_CONTEXT
  #   - echo $CI_PROJECT_DIR
  #   - echo $KANIKO_ARGS
  #   - echo $IMAGE_TAG


build-notifications-api:
  stage: build
  script:
    - echo "build-notifications-api running"
  # extends:
  #   - .kaniko
  # needs: []
  # variables:
  #   DOCKERFILE_PATH: "notifications-api/Dockerfile"
  #   CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/notifications-api"
  #   KANIKO_BUILD_CONTEXT: "notifications-api"
  # script:
  #   - echo $KANIKO_BUILD_CONTEXT
  #   - echo $CI_PROJECT_DIR
  #   - echo $KANIKO_ARGS
  #   - echo $IMAGE_TAG


test-notifications-api:
  stage: test
  script:
    - echo "test-notifications-api running"
  # needs:
  #   - job: build-notifications-api-test-runner
  # image: "$IMAGE_TAG"
  # script:
  #   - cd notifications-api
  #   - pytest --cov=app --cov-report=term --cov-report=xml:coverage.xml
  # coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  # artifacts:
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: notifications-api/coverage.xml


push-image-souvap-notifications-api-job:
  stage: publish
  script:
    - echo "push-image-souvap-notifications-api-job running"
  # needs:
  #   - job: build-notifications-api
  # extends:
  #   - .push-image-souvap
  # variables:
  #   CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/notifications-api"
  #   SOUVAP_IMAGE_NAME: "notifications-api"
