version: '3.0'

services:
  app:
    build:
      context: .
    environment:
      dev_mode: True
    volumes:
      - .:/app
    ports:
      - 8080:80

  test:
    profiles:
      - test
    build:
      target: test
    container_name: notifications-api-test
    volumes:
      - type: bind
        source: ./
        target: /app
