version: '3.0'

services:
  app:
    build:
      context: .
      target: dev
    container_name: notifications-api-dev
    restart: on-failure
    environment:
      DEV_MODE: "True"
      LOG_LEVEL: DEBUG
      SQL_ECHO: "True"
      DATABASE_URL: "postgresql://dev:devpassword@db/dev"

      # Development shall by default not apply migrations, so that while working
      # on a migration it's easily possible to run "alembic upgrade" and
      # "alembic downgrade" without any auto-apply to interfere with it.
      APPLY_DATABASE_MIGRATIONS: False

      # Use in override file if you want to run the app behind a reverse proxy
      # ROOT_PATH: "/univention/portal/notifications-api"

    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8096:8080

  db:
    image: postgres:12.13-alpine
    environment:
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_USER: "dev"
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data

  test:
    profiles:
      - test
    build:
      context: .
      target: test
    container_name: notifications-api-test
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - .:/app

volumes:
  postgresql-data:
