version: '3.0'

services:
  app:
    build:
      context: .
      target: dev
    container_name: notifications-api-dev
    environment:
      dev_mode: True
    volumes:
      - .:/app
    ports:
      - 8096:80

  test:
    profiles:
      - test
    build:
      target: test
    container_name: notifications-api-test
    volumes:
      - .:/app
