version: '3.0'

services:
  app:
    build:
      context: .
      target: dev
    container_name: notifications-api-dev
    environment:
      DEV_MODE: True
      LOG_LEVEL: DEBUG
      DATABASE_URL: "postgresql://dev:devpassword@db/dev"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8096:80

  db:
    image: postgres:12.13-alpine
    environment:
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_USER: "dev"
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data

  redis:
    image: bitnami/redis:7.0.8
    environment:
      - REDIS_PASSWORD=password
      - REDIS_DISABLE_COMMANDS=FLUSHALL,FLUSHDB
      - REDIS_PORT_NUMBER=6379
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis-data
        target: /bitnami/redis/data

  test:
    profiles:
      - test
    build:
      target: test
    container_name: notifications-api-test
    environment:
      LOG_LEVEL: DEBUG
    volumes:
      - .:/app

volumes:
  postgresql-data:
  redis-data:
