# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  app:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
