# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---

# Dummy values for running the Helm linter on the portal-server.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .

## Application-specific
portalServer:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention,dc=test"
  environment: "staging"
  logLevel: "DEBUG"
  ucsInternalUrl: "https://portal.example.develop.souvap-univention.de/univention/internal"
  umcGetUrl: "https://portal.example.develop.souvap-univention.de/univention/internal/umc/get"
  umcSessionUrl: "https://portal.example.develop.souvap-univention.de/univention/internal/umc/get/session-info"
  objectStorageEndpoint: "http://minio:9000"
  objectStorageBucket: "ums"
  objectStorageAccessKeyId: "stub_user"
  objectStorageSecretAccessKey: "stub_password"


## Kubernetes ingress
ingress:
  enabled: false
  host: "portal.example.develop.souvap-univention.de"


## Istio based
istio:
  enabled: true
  host: "portal.example.develop.souvap-univention.de"

## Docker image
image:
  tag: "branch-feature-example"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
