# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "notifications-api.configMap") }}

{{- define "notifications-api.configMap" }}
{{- with .top }}
data:
  APPLY_DATABASE_MIGRATIONS: "{{ .Values.notificationsApi.applyDatabaseMigrations }}"
  {{- if .Values.postgresql.bundled }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "common.names.dependency.fullname" (dict "chartName" "postgresql" "chartValues" .Values.postgresql "context" $.top) }}:{{ .Values.postgresql.primary.service.ports.postgresql }}/{{ .Values.postgresql.auth.database }}"
  {{- else }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.postgresql.connection.host }}:{{ .Values.postgresql.connection.port }}/{{ .Values.postgresql.auth.database }}"
  {{- end }}
  DEV_MODE: "{{ .Values.notificationsApi.devMode }}"
  ENVIRONMENT: "{{ .Values.notificationsApi.environment }}"
  LOG_LEVEL: "{{ .Values.notificationsApi.logLevel }}"
  SQL_ECHO: "{{ .Values.notificationsApi.sqlEcho }}"
  ROOT_PATH: "{{ .Values.notificationsApi.apiPrefix }}"
{{- end }}
{{- end }}
...
