---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: '{{ include "common.names.fullname" . }}'
data:
  ENVIRONMENT: "{{ .Values.portalserver.environment }}"
  LOG_LEVEL: "{{ .Values.portalserver.log_level }}"
  PORTAL_SERVER_ADMIN_GROUP: "{{ .Values.portalserver.admin_group }}"
  PORTAL_SERVER_AUTH_MODE: "{{ .Values.portalserver.auth_mode }}"
  PORTAL_SERVER_EDITABLE: "{{ .Values.portalserver.editable }}"
  PORTAL_SERVER_PORT: "{{ .Values.portalserver.port }}"
  PORTAL_SERVER_UCS_INTERNAL_URL: "{{ .Values.portalserver.ucs_internal_url }}"
  PORTAL_SERVER_UMC_GET_URL: "{{ .Values.portalserver.umc_get_url }}"
  PORTAL_SERVER_UMC_SESSION_URL: "{{ .Values.portalserver.umc_session_url }}"
  PORTAL_SERVER_AUTH_SECRET: "{{ .Values.portalserver.auth_secret }}"

...
