# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
{{ include "common.configMap" (dict "top" . "overrides" "portal-server.configMap") }}

{{- define "portal-server.configMap" }}
{{- with .top }}
data:
  ENVIRONMENT: "{{ .Values.portalServer.environment }}"
  LOG_LEVEL: "{{ .Values.portalServer.logLevel }}"
  PORTAL_SERVER_ADMIN_GROUP: {{ required "The parameter \"portalServer.adminGroup\" is required." .Values.portalServer.adminGroup | quote }}
  PORTAL_SERVER_AUTH_MODE: "{{ .Values.portalServer.authMode }}"
  PORTAL_SERVER_EDITABLE: "{{ .Values.portalServer.editable }}"
  PORTAL_SERVER_PORT: "{{ .Values.portalServer.port }}"
  PORTAL_SERVER_UCS_INTERNAL_URL: {{ required "The parameter \"portalServer.ucsInternalUrl\" is required." .Values.portalServer.ucsInternalUrl | quote }}
  PORTAL_SERVER_UMC_GET_URL: {{ required "The parameter \"portalServer.umcGetUrl\" is required." .Values.portalServer.umcGetUrl | quote }}
  PORTAL_SERVER_UMC_SESSION_URL: {{ required "The parameter \"portalServer.umcSessionUrl\" is required." .Values.portalServer.umcSessionUrl | quote }}
  PORTAL_SERVER_CENTRAL_NAVIGATION_ENABLED: {{ .Values.portalServer.centralNavigation.enabled | quote }}
{{- end }}
{{- end }}
