# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

{{- $_ := required "The UDM Rest API connection has to be configured, udm.connection.url." (coalesce .Values.udm.connection.url .Values.global.udm.connection.url) }}
{{- $_ = required "A UDM password has to be supplied, see parameter udm.auth." (coalesce .Values.udm.auth.password (.Values.udm.auth.existingSecret).name) }}
