# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---
{{ include "common.secret" (dict "top" . "overrides" "portal-server.secret") }}

{{- define "portal-server.secret" }}
{{- with .top }}
data:
  {{- if .Values.portalServer.centralNavigation.enabled }}
  authenticator.secret: {{ .Values.portalServer.centralNavigation.authenticatorSecret | default (randAlphaNum 20) | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
