{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if .Values.portalServer.centralNavigation.enabled }}

{{- $secretName := (include "nubus-common.secrets.name" (dict "defaultNameSuffix" "central-navigation" "context" .)) }}
{{- $sharedSecret := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" $secretName
    "key" "shared_secret"
    "username" "nubus"
    "site" "portal-server-central-navigation"
    "providedValues" (list "portalServer.centralNavigation.auth.sharedSecret")
    "context" .
  )
}}

{{- if not (.Values.portalServer.centralNavigation.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/component: portal-server
  {{- $extraAnnotations := dict }}
  {{- if (.Values.global.secrets).keep }}
    {{- $_ := set $extraAnnotations "helm.sh/resource-policy" "keep" }}
  {{- end }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list $extraAnnotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  shared_secret: {{ $sharedSecret | quote }}
{{- end }}
{{- end }}
