{{- if .Values.portalServer.centralNavigation.enabled }}
---
{{ include "common.secret" (dict "top" . "overrides" "portal-server.secret") }}
{{- end }}

{{- define "portal-server.secret" }}
{{- with .top }}
data:
  authenticator.secret: {{ .Values.portalServer.centralNavigation.authenticatorSecret | default (randAlphaNum 20) | b64enc | quote }}
{{- end }}
{{- end }}
