# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-scripts" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  wait-for-provisioning-api.sh: |
    set -uo pipefail

    retry_interval=2
    response_code=404
    timeout_duration=120
    end_time=$((SECONDS + timeout_duration))

    while [ "$response_code" -ne 200 ]; do
      if [ $SECONDS -ge $end_time ]; then
        echo "Timeout reached. Exiting."
        exit 1
      fi

      echo "Waiting for the Provisioning API to be available ..."
      response_code=$(set +x; curl -s -o response.txt -w "%{http_code}" "${PROVISIONING_API_BASE_URL}/v1/subscriptions/${PROVISIONING_API_USERNAME}" -u "${PROVISIONING_API_USERNAME}":"${PROVISIONING_API_PASSWORD}")
      if [ "${response_code}" -ne 200 ]; then
        echo "Provisioning API is not reachable, status code: $response_code"
        cat response.txt
        sleep ${retry_interval}
      else
        echo "The Provisioning API is reachable"
        exit 0
      fi
    done

    echo "Permanent error ocurred. Exiting."
    exit 1
  wait-for-ldap.sh: |
    #!/bin/bash
    set -euxo pipefail

    while ! ldapsearch -H ldap://$LDAP_HOST -D $LDAP_HOST_DN -y /var/secrets/ldap_password -b "" -s base -LLL; do
      echo "Checking if LDAP Server can be reached..."
      sleep 2
    done

    echo "Success, the LDAP Server is available"
  wait-for-udm.sh: |
    #!/bin/bash
    # TODO: find a way to not leak the udm passwort into the log
    set -euo pipefail

    while ! (set +x; curl -o- --fail --header "Accept: application/json" --user "${PORTAL_UDM_API_USERNAME}:$(cat $PORTAL_UDM_API_PASSWORD_FILE)" "${PORTAL_UDM_API_URL}ldap/base/"); do
      echo "Checking if the UDM REST API can be reached..."
      sleep 2
    done

    echo "Success, the UDM REST API is available"
  wait-for-object-store.py: |
    #!/bin/python3
    import boto3
    import os

    s3 = boto3.resource(
            's3',
            endpoint_url=os.environ["OBJECT_STORAGE_ENDPOINT"],
            aws_access_key_id=os.environ["OBJECT_STORAGE_ACCESS_KEY_ID"],
            aws_secret_access_key=os.environ["OBJECT_STORAGE_SECRET_ACCESS_KEY"]
        )

    provisioned = False
    while not provisioned:
        bucket = s3.Bucket(os.environ["OBJECT_STORAGE_BUCKET"])
        provisioned = bool(bucket.creation_date)
        if not provisioned:
           print("Waiting for the object storage service to be provisioned")
           break
        else:
           print("Object storage already provisioned")
