# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ printf "%s-ucr" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  base-forced.conf: |
    server/role: memberserver
    ldap/master: {{ include "portal-consumer.ldap.connection.host" . }}
    ldap/master/port: {{ include "portal-consumer.ldap.connection.port" . }}
    ldap/hostdn: {{ tpl .Values.ldap.auth.bindDn . }}
    ldap/base: {{ required "The parameter \"portal-consumer.ldapBaseDn\" is required." (include "portal-consumer.ldapBaseDn" .) }}
    {{- $tlsMode := .Values.portalConsumer.tlsMode }}
    directory/manager/starttls: {{ if eq $tlsMode "off" }}0{{ else if eq $tlsMode "unvalidated" }}1{{ else }}2{{ end }}
