{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- $_ := required "Object Storage credentials have to be supplied, see parameter objectStorage.auth." (coalesce (and .Values.objectStorage.auth.secretAccessKey .Values.objectStorage.auth.accessKeyId) (.Values.objectStorage.auth.existingSecret).name) }}
{{- if not (.Values.objectStorage.auth.existingSecret).name }}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "object-storage" "context" .) | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/component: portal-consumer
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
stringData:
  access_key_id: {{ tpl .Values.objectStorage.auth.accessKeyId . | quote }}
  secret_access_key: {{ .Values.objectStorage.auth.secretAccessKey | quote }}
{{- end }}
