# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  serviceName: {{ include "common.names.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.portalConsumer.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        - name: wait-for-ldap
          command: ["/bin/bash", "/scripts/wait-for-ldap.sh"]
          image: "{{ coalesce .Values.waitForDependency.image.registry .Values.global.imageRegistry }}/{{ .Values.waitForDependency.image.repository }}:{{ .Values.waitForDependency.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.waitForDependency.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          env:
            {{- with .Values.waitForDependency.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
          volumeMounts:
            - name: wait-for-ldap
              mountPath: /scripts
            {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
            - name: "secrets"
              mountPath: "{{ .Values.portalConsumer.secretMountPath }}"
            {{- else }}
            {{- include "portal-consumer.secretVolumeMounts" . | nindent 12 }}
            {{- end }}
            {{- if .Values.waitForDependency.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.waitForDependency.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
        - name: wait-for-udm
          command: ["/bin/bash", "/scripts/wait-for-udm.sh"]
          image: "{{ coalesce .Values.waitForDependency.image.registry .Values.global.imageRegistry }}/{{ .Values.waitForDependency.image.repository }}:{{ .Values.waitForDependency.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.waitForDependency.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          env:
            {{- with .Values.waitForDependency.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
          volumeMounts:
            - name: wait-for-udm
              mountPath: /scripts
            {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
            - name: "secrets"
              mountPath: "{{ .Values.portalConsumer.secretMountPath }}"
            {{- else }}
            {{- include "portal-consumer.secretVolumeMounts" . | nindent 12 }}
            {{- end }}
            {{- if .Values.waitForDependency.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.waitForDependency.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
        - name: wait-for-object-storage
          command: ["/usr/bin/python3", "/scripts/wait-for-object-store.py"]
          image: "{{ coalesce .Values.portalConsumer.image.registry .Values.global.imageRegistry }}/{{ .Values.portalConsumer.image.repository }}:{{ .Values.portalConsumer.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.portalConsumer.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
          env:
            - name: OBJECT_STORAGE_ACCESS_KEY_ID
              {{- include "portal-consumer.objectStorageAccessKeyId" . | nindent 14 }}
            - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
              {{- include "portal-consumer.objectStorageSecretAccessKey" . | nindent 14 }}
            {{- with .Values.waitForDependency.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: wait-for-object-store
              mountPath: /scripts
            {{- if .Values.waitForDependency.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.waitForDependency.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
        - name: wait-for-provisioning-api
          image: "{{ coalesce .Values.waitForDependency.image.registry .Values.global.imageRegistry }}/{{ .Values.waitForDependency.image.repository }}:{{ .Values.waitForDependency.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.waitForDependency.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          command: ["/bin/bash", "-c", "/scripts/wait-for-provisioning-api.sh ${PROVISIONING_API_BASE_URL}/subscriptions/v1/subscriptions/${PROVISIONING_API_USERNAME} -u ${PROVISIONING_API_USERNAME}:${PROVISIONING_API_PASSWORD}"]
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
          volumeMounts:
            - name: wait-for-provisioning-api
              mountPath: /scripts
          env:
            - name: PROVISIONING_API_PASSWORD
              {{- include "portal-consumer.provisioningApi.auth.password" . | nindent 14 }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
      containers:
        - name: "portal-consumer"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ coalesce .Values.portalConsumer.image.registry .Values.global.imageRegistry }}/{{ .Values.portalConsumer.image.repository }}:{{ .Values.portalConsumer.image.tag }}"
          imagePullPolicy: {{ coalesce .Values.portalConsumer.image.imagePullPolicy .Values.global.imagePullPolicy | quote }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-common" (include "common.names.fullname" .) }}
          env:
            - name: OBJECT_STORAGE_ACCESS_KEY_ID
              {{- include "portal-consumer.objectStorageAccessKeyId" . | nindent 14 }}
            - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
              {{- include "portal-consumer.objectStorageSecretAccessKey" . | nindent 14 }}
            - name: PROVISIONING_API_PASSWORD
              {{- include "portal-consumer.provisioningApi.auth.password" . | nindent 14 }}
            {{- with .Values.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: group-membership-cache
              mountPath: /usr/share/univention-group-membership-cache/caches
            {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
            - name: "secrets"
              mountPath: "{{ .Values.portalConsumer.secretMountPath }}"
            {{- else }}
            {{- include "portal-consumer.secretVolumeMounts" . | nindent 12 }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" .) | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: wait-for-object-store
          configMap:
            name: {{ printf "%s-common" (include "common.names.fullname" .) }}
        - name: wait-for-udm
          configMap:
            name: {{ printf "%s-common" (include "common.names.fullname" .) }}
        - name: wait-for-ldap
          configMap:
            name: {{ printf "%s-common" (include "common.names.fullname" .) }}
        - name: "wait-for-provisioning-api"
          configMap:
            defaultMode: 0555
            name: {{ printf "%s-wait-for-provisioning-api" (include "common.names.fullname" .) }}
        {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
        - name: "secrets"
          secret:
            secretName: {{ printf "%s-common" (include "common.names.fullname" .) }}
        {{- else }}
        {{- if (include "portal-consumer.ldap.credentialSecret.name" . ) }}
        - name: {{ printf "%s-volume" (include "portal-consumer.ldap.credentialSecret.name" . ) | quote }}
          secret:
            secretName: {{ (include "portal-consumer.ldap.credentialSecret.name" . ) | quote }}
        {{- end }}
        {{- if (include "portal-consumer.ldap.tlsSecret.name" . ) }}
        - name: {{ printf "%s-volume" (include "portal-consumer.ldap.tlsSecret.name" . ) | quote }}
          secret:
            secretName: {{ (include "portal-consumer.ldap.tlsSecret.name" . ) | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
        {{- if .Values.waitForDependency.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.waitForDependency.extraVolumes  "context" .) | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: group-membership-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.groupMembershipCache.storageClass }}
      storageClassName: {{ .Values.persistence.groupMembershipCache.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.groupMembershipCache.size | required ".Values.persistence.groupMembershipCache.size is required" | quote }}
