---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Dummy values for running the Helm linter on the portal-consumer.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .

## Application-specific
portalConsumer:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention-organization,dc=intranet"
  environment: "staging"
  logLevel: "DEBUG"
  umcGetUrl: "http://umc-server/get"
  umcSessionUrl: "http://umc-server/get/session-info"
  ucsInternalPath: "portal-data"
  assetsRootPath: "portal-assets"
  tlsMode: "unvalidated"
  objectStorageAccessKeyId: "stub_user"
  objectStorageSecretAccessKey: "stub_password"
  ldapBaseDn: "example.test"
  ldapHost: "ldap.example.test"
  ldapHostDn: "example.test"
  ldapPort: "437"
  udmApiUrl: "http://udm-server/udm"

provisioningApi:
  connection:
    baseUrl: "http://provisioning-api-server"
  auth:
    username: "portal-consumer"
    password: "password"
    existingSecret: null

objectStorage:
  endpoint: "http://minio:9000"
  bucketName: "ums"
  auth:
    accessKeyId: "accessKey"
    secretAccessKey: "secretKey"
    existingSecret: null

## Kubernetes ingress
ingress:
  enabled: false
  host: "localhost"


## Docker image
image:
  tag: "latest"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

ldap:
  connection:
    host: "ldap-server"
    port: "7389"
  auth:
    password: "ldapPassword"
    existingSecret: null
  tls:
    enabled: true
    existingSecret: null
