version: '3.3'

# TODO: The config files are dynamic, currently mounting something as stub
# to get something into a running state.

services:
  portal-server:
    platform: "linux/amd64"
    build:
      context: ../
      dockerfile: images/portal-server/Dockerfile
    container_name: portal-server
    environment:
      LDAP_HOSTDN: "stub_ldap_hostdn"
      UCS_HOSTNAME: "stub_ucs_hostname"
      LDAP_SERVER_NAME: "stub_ldap_server_name"
    ports:
      - "8095:8095"
    volumes:
      - type: bind
        source: ./portal-server/config.json
        target: /usr/lib/univention-portal/config/config.json
      - type: bind
        source: ./portal-server/groups.json
        target: /var/cache/univention-portal/groups.json
      - type: bind
        source: ./portal-server/portal.json
        target: /var/cache/univention-portal/portal.json
  apache:
    platform: "linux/amd64"
    container_name: apache
    build:
      context: ../
      dockerfile: images/apache/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./apache/univention-portal.conf
        target: /etc/apache2/sites-available/univention-portal.conf
      - type: bind
        source: ./apache/ucs-sites-univention-portal.conf
        target: /etc/apache2/ucs-sites.conf.d/univention-portal.conf
