---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'

include:
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.66.2"
    file:
      - "defaults/stages.yaml"
      - "templates/buildkit.yaml"
      - "jobs/container-build-external-buildkit.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"

generate-joinscript-data:
  stage: "prepare"
  image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/stack-data/joinscript-tools:latest"
  needs: []
  script:
    - |
      ucr set \
        ldap/base="{{ ldap_base }}" \
        server/role="domaincontroller_master"
      # Ensure that the icons can be found by the calls to base64
      ln -s "$PWD" "/usr/share/univention-portal"
      mkdir --parents $(dirname ${OUT_FILENAME})
      ./33univention-portal.inst || true
  variables:
    OUT_FILENAME: "udm/join-data/univention-portal.yaml.j2"
  artifacts:
    paths:
      - "udm/join-data"

.build-matrix: &build-matrix
  - IMAGE_NAME: "portal-server"
  - IMAGE_NAME: "portal-extension"

.post-build-matrix: &post-build-matrix
  - IMAGE_NAME:
      - "portal-server-test-runner"
      - "portal-server"
      - "portal-extension"
      - "portal-consumer"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "portal-server"
      - "portal-consumer"
      - "portal-extension"

container-build:
  parallel:
    matrix: *build-matrix
  variables:
    BUILD_CONTEXT: "$CI_PROJECT_DIR"
    DOCKERFILE_PATH: "docker/${IMAGE_NAME}/Dockerfile"

build-portal-server-test-runner:
  stage: "build"
  extends: ".buildkit"
  variables:
    IMAGE_NAME: "portal-server-test-runner"
    DOCKERFILE_PATH: "docker/portal-server/Dockerfile"
    BUILD_TARGET: "test"
    BUILD_CONTEXT: "$CI_PROJECT_DIR"

container-malware-scan:
  parallel:
    matrix: *publish-matrix

container-build-portal-consumer:
  stage: "build"
  extends: ".buildkit"
  needs:
    # depends on portal-server
    - job: "container-build"
      artifacts: false
  variables:
    IMAGE_NAME: "portal-consumer"
    DOCKERFILE_PATH: "docker/portal-consumer/Dockerfile"
    BUILD_CONTEXT: "$CI_PROJECT_DIR"
    BUILD_ARGS: "--opt build-arg:PORTAL_BASE_IMAGE_TAG=${RELEASE_VERSION}"

test-portal-server:
  stage: "test"
  needs:
    - build-portal-server-test-runner
  image: "$CI_REGISTRY_IMAGE/portal-server-test-runner:${RELEASE_VERSION}"
  variables:
    OBJECT_STORAGE_ENDPOINT: "stub_minio"
    OBJECT_STORAGE_BUCKET: "stub_bucket"
    OBJECT_STORAGE_ACCESS_KEY_ID: "stub_user"
    OBJECT_STORAGE_SECRET_ACCESS_KEY: "stub_value"
    PORTAL_SERVER_ADMIN_GROUP: "cn=Domain Admins,cn=groups,dc=univention,dc=test"
    PORTAL_SERVER_UCS_INTERNAL_PATH: "portal-data"
    PORTAL_SERVER_UMC_GET_URL: "stub-umc-get-urll"
    PORTAL_SERVER_UMC_SESSION_URL: "stub-umc-session-url"
  script:
    - pip3 install -e . -r requirements-test.txt --no-deps --no-build-isolation
    - >
      pytest
      --cov=python/univention/portal
      --cov-report=term
      --cov-report=xml:coverage.xml
      unittests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: "cobertura"
        path: "coverage.xml"

test-chart-portal-server:
  stage: test
  needs: []
  image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.29.10@sha256:5cba2a8fc4c6d5fa82bcec177ad433ab74695b4e02b2a2e9ed9b53c734b34dbf"
  script:
    - helm dep build helm/portal-server
    - pytest portal-server/tests/chart

test-chart-portal-consumer:
  stage: test
  needs: []
  image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.29.10@sha256:5cba2a8fc4c6d5fa82bcec177ad433ab74695b4e02b2a2e9ed9b53c734b34dbf"
  script:
    - helm dep build helm/portal-consumer
    - pytest portal-consumer/tests/chart

push-image-external:
  before_script:
    - |
      set -eux
      export EXTERNAL_REGISTRY_ROBOT_ACCOUNT='robot$nubus-push-from-gitlab'
      echo /bin/skopeo login \
          --username "${EXTERNAL_REGISTRY_ROBOT_ACCOUNT}" \
          --password-stdin "${EXTERNAL_REGISTRY_HOST}" \
          --authfile "${HOME}/external-auth.json"
  parallel:
    matrix: *publish-matrix

container-sign-external:
  parallel:
    matrix: *publish-matrix

container-release-attestation:
  needs:
    - push-image-external
  parallel:
    matrix: *publish-matrix

package-helm-charts:
  parallel:
    matrix:
      - IMAGE_NAME:
          - "portal-server"
          - "portal-consumer"

...
