# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH
---

portalConsumer:
  ldapHost: "kyverno"
  ldapPort: 123
  udmApiUrl: "kyverno"

provisioningApi:
  connection:
    baseUrl: "kyverno"
  auth:
    username: "kyverno"
    password: "kyverno"

...
