#!/bin/sh
#
# Univention Management Console
#  prerm script for the debian package
#
# Like what you see? Join us!
# https://www.univention.com/about-us/careers/vacancies/
#
# Copyright 2018-2022 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/univention/templates/files/usr/share/univention-portal/apps.json 4.0.5-64~ -- "$@"
# End automatically added section
# Automatically added by univention-install-config-registry
if [ "$1" = "remove" ] && [ -e /etc/univention/templates/info/univention-portal.info ] ; then
  [ -x /usr/sbin/univention-config-registry ] && univention-config-registry unregister univention-portal || true
  mv /etc/univention/templates/info/univention-portal.info /etc/univention/templates/removed/univention-portal.info || true
fi
# End automatically added section


a2dissite univention-portal.conf

exit 0
