# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---

collections:
  # 3rd party
  - name: "ansible.utils"
    version: "2.2.0"
    source: "https://galaxy.ansible.com"
  - name: "ansible.netcommon"
    version: "2.1.0"
    source: "https://galaxy.ansible.com"
  - name: "ansible.posix"
    version: "1.2.0"
    source: "https://galaxy.ansible.com"
  - name: "community.general"
    version: "3.1.0"
    source: "https://galaxy.ansible.com"
  - name: "community.crypto"
    version: "1.6.2"
    source: "https://galaxy.ansible.com"
  # univention
  - name: "univention.ucs_modules"
    version: "0.0.4-alpha"
    source: "https://galaxy.ansible.com"
  - name: "univention.ucs_roles"
    version: "1.16.4"
    source: "https://galaxy.ansible.com"
