- name: Ensure the portal repository is present and up to date
  hosts: jbornhold_clean
  remote_user: user
  vars:
    url_prefix: "univention"
    url_suffix: "-container"
    ucs_host: "ucs-5746.univention.intranet"
    ports:
      portal_server: "9095"
      portal_frontend: "9080"

  tasks:
    - name: Ensure the configuration file directory exists
      ansible.builtin.file:
        path: /etc/spike-epic-409
        state: directory
        mode: "0755"

    - name: Prepare the portal configuration config.json
      ansible.builtin.template:
        src: ./etc/portal-config.json.j2
        dest: /etc/spike-epic-409/portal-config.json

    - name: Checkout the portal repository
      ansible.builtin.git:
        repo: "git@git.knut.univention.de:univention/components/univention-portal.git"
        dest: /home/user/univention-portal
        # You may want to pin this to a specific commit to avoid rebuilding the
        # frontend image too frequencly. It is taking time.
        version: origin/jbornhold/409-concept-and-planning

    - name: Build docker image backend
      ansible.builtin.command:
        cmd: docker build -t portal-server -f docker/portal-server/Dockerfile .
        chdir: /home/user/univention-portal

    - name: Build docker image frontend
      community.docker.docker_image:
        name: portal-frontend
        build:
          dockerfile: docker/frontend/Dockerfile
          path: /home/user/univention-portal
        source: build

    - name: Run the portal server container
      community.docker.docker_container:
        name: portal-server
        state: started
        detach: true
        image: portal-server
        published_ports:
          - "{{ ports.portal_server }}:80"
        mounts:
          # The configuration is currently provided as a file.
          # This has to be provided by the environment.
          - source: /etc/spike-epic-409/portal-config.json
            target: /usr/lib/univention-portal/config/config.json
            type: bind
          # The environment has to provide this data and ensure that it
          # will stay up to date. The portal server just expects it to be
          # provided and will use it.
          - source: /var/cache/univention-portal/portal.json
            target: /var/cache/univention-portal/portal.json
            type: bind
          - source: /var/cache/univention-portal/groups.json
            target: /var/cache/univention-portal/groups.json
            type: bind

    - name: Run the portal frontend container
      community.docker.docker_container:
        name: portal-frontend
        state: started
        detach: true
        image: portal-frontend
        published_ports:
          - "{{ ports.portal_frontend }}:80"

    - name: Ensure Apache configuration for backend container
      ansible.builtin.template:
        src: etc/exp-univention-portal-container.conf.j2
        dest: /etc/apache2/ucs-sites.conf.d/exp-univention-portal-container.conf

    - name: Reload Apache configuration
      ansible.builtin.service:
        name: apache2
        state: reloaded
