---
- name: Fetch secrets from UCS machine
  hosts: ucs_primary

  tasks:
  - name: Fetch LDAP password
    ansible.builtin.fetch:
      src: /etc/ldap.secret
      dest: ../docker/secret/ldap.secret
      flat: true

  - name: Fetch machine.secret
    ansible.builtin.fetch:
      src: /etc/machine.secret
      dest: ../docker/secret/machine.secret
      flat: true

  - name: Register LDAP password
    ansible.builtin.slurp:
      src: /etc/ldap.secret
    register: ldap_secret

  - name: Fetch CAcert.pem
    ansible.builtin.fetch:
      src: /etc/univention/ssl/ucsCA/CAcert.pem
      dest: ../docker/ssl/certs/CAcert.pem
      flat: true

  - name: Register CAcert.pem
    ansible.builtin.slurp:
      src: /etc/univention/ssl/ucsCA/CAcert.pem
    register: ca_cert

  - name: Fetch cert.pem
    ansible.builtin.fetch:
      src: /etc/univention/ssl/{{ ansible_fqdn}}/cert.pem
      dest: ../docker/ssl/certs/cert.pem
      flat: true

  - name: Register cert.pem
    ansible.builtin.slurp:
      src: /etc/univention/ssl/{{ ansible_fqdn}}/cert.pem
    register: cert_pem

  - name: Register LDAP base from UCR
    ansible.builtin.command: ucr get ldap/base
    register: ldap_base

  - name: Register LDAP host dn from UCR
    ansible.builtin.command: ucr get ldap/hostdn
    register: ldap_hostdn

  - name: Register LDAP portal_default_dn from UCR
    ansible.builtin.command: ucr get portal/default-dn
    register: portal_default_dn

  - name: Configure .env.listener
    ansible.builtin.template:
      src: ./templates/dotenv.listener.j2
      dest: ../docker/.env.listener
    delegate_to: localhost

  - name: Configure docker-compose.override.yaml
    ansible.builtin.template:
      src: ./templates/docker-compose.override.yaml.j2
      dest: ../docker/docker-compose.override-generated.yaml
    delegate_to: localhost

  # Assembling the file on the UCS machine since the hashing functions
  # cause trouble on some local systems.
  - name: Create store-dav htpasswd file - portal-server
    community.general.htpasswd:
      path: /tmp/store-dav-htpasswd
      name: portal-server
      password: "{{ ucs_auth_secret }}"

  - name: Create store-dav htpasswd file - portal-listener
    community.general.htpasswd:
      path: /tmp/store-dav-htpasswd
      name: portal-listener
      password: "{{ ucs_auth_secret }}"

  - name: Fetch store-dav htpasswd file
    ansible.builtin.fetch:
      src: /tmp/store-dav-htpasswd
      dest: ../docker/secret/store-dav-htpasswd
      flat: true
