- name: Fix the date and time inside of the VM
  hosts: jbornhold_clean

  tasks:
    - name: Run rdate to fix up date and time
      ansible.builtin.shell: rdate -n "$(ucr get gateway)"
      register: result

    - name: Debug output VM date
      ansible.builtin.debug:
        msg: "System {{ inventory_hostname }} time: {{ result.stdout }}"
