vm:
  hosts:
    jbornhold_test:
      ansible_host: 10.200.115.10
    jbornhold_clean:
      # Clean UCS system install, then snapshotted
      ansible_host: 10.200.115.20
  vars:
    ansible_user: root

vmhosts:
  hosts:
    skurup:
      ansible_host: skurup.knut.univention.de
    vars:
      ansible_user: jbornhold
