---
- name: Install / set up / remove kind environment
  hosts: '{{ nodes | default("ucs_dev_machines") }}'
  gather_facts: no
  vars_files:
    - vars/k8s-kind.yaml

  tasks:
    - include_role:
        name: kind
      tags: [ install ]

    - include_role:
        name: kubectl
      tags: [ install ]

    - include_role:
        name: helm
      tags: [ install ]

    - include_role:
        name: tilt
      tags: [ install ]

    - name: Make sure apache is not running when ingress requested
      ansible.builtin.systemd:
        name: apache2
        state: stopped
        masked: true
#      when: ingress_enable
      tags: [ never ]

    - name: Set up kind cluster with local Docker registry
      ansible.builtin.shell: |
        cat <<EOF | ctlptl apply -f -
        {{ lookup("template", playbook_dir ~ "/templates/k8s/setup-kind-cluster.yaml.j2") }}
        EOF
      args:
        executable: /bin/bash
      tags: [ setup ]

    - name: Install ingress-nginx
      ansible.builtin.shell: |
        cat <<EOF | kubectl apply -f -
        {{ lookup("template", playbook_dir ~ "/templates/k8s/deploy-ingress-nginx.yaml") }}
        EOF
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=90s
      args:
        executable: /bin/bash
      tags: [ setup-ingress-controller ]

    - name: Tear down kind cluster
      ansible.builtin.shell: 'ctlptl delete cluster kind-{{ cluster_name }}'
      args:
        executable: /bin/bash
      register: teardown_cluster
      tags: [ teardown ]

    - name: Restart apache when ingress had been requested
      ansible.builtin.systemd:
        name: apache2
        state: started
        masked: false
#      when: ingress_enable
      tags: [ never ]

    - include_role:
        name: tilt
      tags: [ remove ]

    - include_role:
        name: helm
      tags: [ remove ]

    - include_role:
        name: kubectl
      tags: [ remove ]

    - include_role:
        name: kind
      tags: [ remove ]
