---
- name: Setup Python3 virtual env on remote VM
  hosts: ucs_dev_machines
  gather_facts: no
  vars_files:
    - vars/venv.yaml

  tasks:
    - name: Install system packages
      apt:
        pkg:
          - apt-transport-https
          - build-essential
          - libffi-dev
          - python3-dev
          - python3-venv
        update_cache: yes
      tags: [ install ]

    - name: Check if pip is installed
      shell: which pip3
      register: pip3_available
      ignore_errors: yes
      tags: [ always ]

    - name: Install pip
      shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python3
      when: pip3_available is failed
      tags: [ install ]

    - name: Install Python packages
      pip:
        name:
          - docker
        virtualenv: "{{ venv_path }}"
        virtualenv_command: "{{ venv_command }}"
      tags: [ install ]
