- name: Make UCS machine usable from Kubernetes
  hosts: ucs_vms
  vars:
    url_prefix: "univention"
    url_suffix: ""

  tasks:

    - name: Fake client IP for UMC
      ansible.builtin.template:
        src: ./etc/exp-univention-umc-hack.conf.j2
        dest: /etc/apache2/sites-enabled/010-exp-univention-umc-hack.conf

    - name: Reload Apache configuration
      ansible.builtin.service:
        name: apache2
        state: reloaded

    # TODO: Stop the local portal server
    # TODO: Stop serving the frontend
