---
# Default values for univention-portal-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


## Application-specific
portalfrontend:
  environment: "production"
  log_level: "WARNING"

## Kubernetes ingress
ingress:
  enabled: false
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/use-regex: "true"
  ## Define Hostname
  # host: "portal.example.com"
  paths:
    - pathType: Exact
      path: /univention/portal/($|index.html$)
    - pathType: Prefix
      path: /univention/portal/(css/.*)
    - pathType: Prefix
      path: /univention/portal/(fonts/.*)
    - pathType: Prefix
      path: /univention/portal/(i18n/.*)
    - pathType: Prefix
      path: /univention/portal/(media/.*)
    - pathType: Prefix
      path: /univention/portal/(js/.*)
    - pathType: Prefix
      path: /univention/portal/(oidc/.*)
  tls:
    enabled: true
    secretName: ""


## Istio support
istio:
  enabled: true
  ## Define Hostname
  # host: "portal.example.com"
  virtualService:
    enabled: true
    annotations: {}
    # pathOverrides:
    #   - match: "exact"
    #     path: "/univention/portal/css/custom.css"
    #     route:
    #       - destination:
    #           port:
    #             number: 80
    #           host: "example-service"
    paths:
      # TODO: Istio does currently not support a URL rewrite which uses regular
      # expressions, basically the capture groups are not yet supported. It also
      # does not support an automatic sorting of rules based on the prefix
      # length like the nginx ingress does. Interim we mention explicitly every
      # prefix which is exclusively part of the frontend in this configuration.
      # This way all other subpaths in "/univention/portal/" can still be
      # reliably grabbed by other services if they are present.
      - match: "prefix"
        path: "/univention/portal/css/"
        rewrite: "/css/"
      - match: "prefix"
        path: "/univention/portal/fonts/"
        rewrite: "/fonts/"
      - match: "prefix"
        path: "/univention/portal/i18n/"
        rewrite: "/i18n/"
      - match: "exact"
        path: "/univention/portal/"
        rewrite: "/"
      - match: "exact"
        path: "/univention/portal/index.html"
        rewrite: "/index.html"
      - match: "prefix"
        path: "/univention/portal/media/"
        rewrite: "/media/"
      - match: "prefix"
        path: "/univention/portal/js/"
        rewrite: "/js/"
      - match: "prefix"
        path: "/univention/portal/oidc/"
        rewrite: "/oidc/"
  gateway:
    enabled: false
    annotations:
    selectorIstio: "ingressgateway"
    externalGatewayName: "swp-istio-gateway"
    tls:
      enabled: true
      httpsRedirect: true
      secretName: ""


## Docker image
image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/univention-portal/portal-frontend"
  imagePullPolicy: "Always"
  tag: "latest"

  ## Define image sha256 as an alternative to `tag`
  # sha256:


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


## Deployment resources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "4Gi"
    cpu: "4"

## Kubernetes Service
service:
  enabled: true
  type: "ClusterIP"
  ports:
    http:
      containerPort: 80
      port: 80
      protocol: "TCP"

  sessionAffinity:
    enabled: false
    timeoutSeconds: 10800

...
