---

# SPDX-FileCopyrightText: 2023-2024 Univention GmbH
# SPDX-License-Identifier: AGPL-3.0-only

# Deployment-specific values for the `example` environment for portal-server.
# This is a YAML-formatted file.
# Include the file with the `--values` parameter


## Application-specific
portalConsumer:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention,dc=test"
  environment: "staging"
  logLevel: "DEBUG"
  assetsRoot: "http://portal-consumer:univention@portal-consumer-store-dav/portal-assets/"
  ucsInternalUrl: "http://portal-consumer:univention@portal-consumer-store-dav/portal-data"
  umcGetUrl: "http://ucs-machine/univention/internal/umc/get"
  umcSessionUrl: "http://ucs-machine/univention/internal/umc/get/session-info"

  authLdapSecret: "top-secret-value"
  ldapBaseDn: "dc=univention-organization,dc=intranet"
  ldapHost: "ldap-server"
  # TODO: This should not be required, the machine account is not there
  # ldapHostDn: cn=stub-value,cn=dc,cn=computers,dc=univention-organization,dc=intranet
  ldapHostDn: "cn=admin,dc=univention-organization,dc=intranet"
  machineSecret: "top-secret-value"
  portalDefaultDn: "cn=domain,cn=portal,cn=portals,cn=univention,dc=univention-organization,dc=intranet"
  udmApiUrl: "http://udm-rest-api/udm/"
  udmApiUsername: "cn=admin"

  tlsMode: "off"

storeDav:
  bundled: true

  image:
    registry: "gitregistry.knut.univention.de"
    repository: "univention/customers/dataport/upx/container-store-dav/store-dav"
    pullPolicy: "IfNotPresent"
    tag: "latest"

  # image:
  #   registry: "local"
  #   repository: "store-dav"
  #   pullPolicy: "IfNotPresent"
  #   tag: "latest"

  storeDav:
    # Example, password set to "univention"
    authHtpasswd: |
      portal-server:$apr1$yruGWANI$75Soiqs3hEmezu.g/r3VW/
      portal-consumer:$apr1$6kadQ4Ji$hHriD5fpBJyf00SIy.NG41

  ingress:
    enabled: true
    host: "localhost"
    tls:
      enabled: false

  istio:
    enabled: false


## Docker image
# image:
#   registry: "gitregistry.knut.univention.de"
#   repository: "univention/components/univention-portal/portal-consumer"
#   pullPolicy: "IfNotPresent"
#   tag: "latest"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
