---
# Deployment-specific values for the `example` environment for portal-server.
# This is a YAML-formatted file.
# Include the file with the `--values` parameter


## Application-specific
portalListener:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention,dc=test"
  environment: "staging"
  logLevel: "DEBUG"
  assetsRoot: "http://portal-listener:univention@portal-listener-store-dav/portal-assets/"
  ucsInternalUrl: "http://portal-listener:univention@portal-listener-store-dav/portal-data/"
  umcGetUrl: "http://ucs-machine/univention/internal/umc/get"
  umcSessionUrl: "http://ucs-machine/univention/internal/umc/get/session-info"


storeDav:
  bundled: true

  image:
    registry: "gitregistry.knut.univention.de"
    repository: "univention/customers/dataport/upx/container-store-dav/store-dav"
    pullPolicy: "IfNotPresent"
    tag: "latest"

  # image:
  #   registry: "local"
  #   repository: "store-dav"
  #   pullPolicy: "IfNotPresent"
  #   tag: "latest"

  storeDav:
    # Example, password set to "univention"
    authHtpasswd: |
      portal-server:$apr1$yruGWANI$75Soiqs3hEmezu.g/r3VW/
      portal-listener:$apr1$6kadQ4Ji$hHriD5fpBJyf00SIy.NG41

  ingress:
    enabled: true
    host: "localhost"
    tls:
      enabled: false

  istio:
    enabled: false


## Docker image
# image:
#   registry: "gitregistry.knut.univention.de"
#   repository: "univention/components/univention-portal/portal-listener"
#   pullPolicy: "IfNotPresent"
#   tag: "latest"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
