# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---
# Deployment-specific values for the `example` environment for portal-server.
# This is a YAML-formatted file.
# Include the file with the `--values` parameter


## Application-specific
portalServer:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention,dc=intranet"
  environment: "staging"
  editable: "true"
  logLevel: "DEBUG"
  ucsInternalUrl: "http://portal-server:univention@portal-listener-store-dav/portal-data"
  umcGetUrl: "https://portal-server:univention@portal.example.develop.souvap-univention.de/univention/internal/umc/get"
  umcSessionUrl: "https://portal-server:univention@portal.example.develop.souvap-univention.de/univention/internal/umc/get/session-info"


## Kubernetes ingress
ingress:
  enabled: false
  host: "portal.example.develop.souvap-univention.de"


## Istio based
istio:
  enabled: true
  host: "portal.example.develop.souvap-univention.de"

## Docker image
image:
  tag: "branch-feature-example"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
