---
apiVersion: "v2"
type: "application"
name: "portal-listener"
description: "A Helm chart for the Univention Portal Listener"
home: "https://www.univention.de/"

# Chart version
# Apply Semantic Versioning (https://semver.org/)
version: "0.1.0"

# Portal Version
appVersion: "1.16.0"

dependencies:
  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.2.0"
  - name: "store-dav"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/container-store-dav/helm"
    version: "^0.2.0"
    condition: "store-dav.bundled"

...
