---

# Dummy values for running the Helm linter on the portal-listener.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .

## Application-specific
portalListener:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention,dc=test"
  environment: "staging"
  logLevel: "DEBUG"
  ucsInternalUrl: "https://portal.example.develop.souvap-univention.de/univention/internal"
  umcGetUrl: "https://portal.example.develop.souvap-univention.de/univention/internal/umc/get"
  umcSessionUrl: "https://portal.example.develop.souvap-univention.de/univention/internal/umc/get/session-info"
  ldapSecret: "s3cr3t"
  ldapSecretFile: "/var/secrets/ldap_secret"
  machineSecret: "s3cr3t"
  machineSecretFile: "/var/secrets/machine_secret"
  caCert: "s3cr3t"
  caCertFile: "/var/secrets/ca_cert"
  tlsMode: "unvalidated"


## Kubernetes ingress
ingress:
  enabled: false
  host: "portal.example.develop.souvap-univention.de"


## Istio based
istio:
  enabled: true
  host: "portal.example.develop.souvap-univention.de"

## Docker image
image:
  tag: "branch-feature-example"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
