# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023 Univention GmbH

---

# Dummy values for running the Helm linter on the portal-listener.
# Run it like this: helm lint -f values.yaml -f linter_values.yaml .

## Application-specific
portalListener:
  adminGroup: "cn=Domain Admins,cn=groups,dc=univention-organization,dc=intranet"
  environment: "staging"
  logLevel: "DEBUG"
  assetsRoot: "http://portal-listener:password@store-dav/portal-assets/"
  ucsInternalUrl: "http://portal-listener:password@store-dav/portal-data"
  umcGetUrl: "http://umc-server/get"
  umcSessionUrl: "http://umc-server/get/session-info"
  ldapSecret: "password"
  ldapSecretFile: "/var/secrets/ldap_secret"
  machineSecret: "password"
  machineSecretFile: "/var/secrets/machine_secret"
  tlsMode: "unvalidated"

store-dav:
  bundled: false

## Kubernetes ingress
ingress:
  enabled: false
  host: "localhost"


## Istio based
istio:
  enabled: true
  host: "localhost"

## Docker image
image:
  tag: "latest"


## Container deployment probes
probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

...
