# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2024 Univention GmbH

---
# Default values for univention-portal-listener
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


# -- Application configuration of the Portal Listener
portalListener:
  port: "80"
  # Update configuration to mach the needs of the portal listener
  # -- Define LDAP Admin Group.
  # Example: `"cn=Domain Admins,cn=groups,dc=example,dc=com"`
  adminGroup: null
  # -- Where to store the assets inside the object storage bucket, e.g. portal entry icons
  assetsRootPath: "portal-assets"
  # -- Define the authentication mode for the portal. Use "ucs" or "saml".
  authMode: "ucs"
  # -- CA root certificate, base64-encoded. Optional; will be written to "caCertFile" if set.
  caCert: ""
  certPem: ""
  # -- The path to the "caCertFile" docker secret or a plain file.
  caCertFile: "/run/secrets/ca_cert"
  # -- Whenever to start encryption and validate certificates.
  # Chose from "off", "unvalidated" and "secure".
  tlsMode: "secure"
  # -- Internal domain name of the UCS machine
  domainName: "univention.intranet"
  # -- Debug level of the listener
  debugLevel: "4"
  # -- Defines if members of the Admin group can use the edit mode in the portal.
  editable: "true"
  # -- TODO: Clarify usage of this parameter
  environment: "production"

  # -- Base DN of the LDAP directory
  ldapBaseDn: null
  # -- LDAP password for `cn=admin`. Will be written to "ldapSecretFile" if set.
  ldapSecret: null
  # -- The path to the "ldapSecretFile" docker secret or a plain file
  ldapSecretFile: "/var/secrets/ldap_secret"
  # -- Hostname of the LDAP server
  ldapHost: null
  # -- The IP address of the LDAP server.
  ldapHostIp: null
  # -- DN of the UCS machine
  ldapHostDn: null
  # -- Port to connect to the LDAP server.
  ldapPort: "389"

  # -- TODO: Clarify usage of this parameter
  logLevel: "WARNING"
  # -- LDAP password for `ldapHostDn`. Will be written to "machineSecretFile" if set.
  machineSecret: null
  # -- The path to the "machineSecretFile" docker secret or a plain file
  machineSecretFile: "/var/secrets/machine_secret"
  # -- Hostname where the notifier can be reached.
  notifierServer: null
  # -- DN of the default portal
  portalDefaultDn: null

  # -- UDM API connection URL
  udmApiUrl: null
  # -- UDM API username.
  udmApiUsername: "cn=admin"
  # -- UDM API password file.
  #    Default: same as `machineSecretFile`.
  udmApiSecretFile: "/var/secrets/machine_secret"

  # -- Define UCS internal endpoint where the portal, selfservice and groups are defined
  # Example: `"https://portal.example.com/univention/internal"`
  ucsInternalPath: "portal-data"
  # -- Define UMC get endpoint.
  # Example: `"https://portal.example.com/univention/internal/umc/get"`
  umcGetUrl: null
  # -- Define UMC session-info" endpoint.
  # Example: `"https://portal.example.com/univention/internal/umc/get/session-info"`
  umcSessionUrl: null
  # -- Object storage endpoint
  objectStorageEndpoint: "http://ums-minio:9000"
  # -- Bucket in the object storage for storing the portal and assets
  objectStorageBucket: "ums"
  # -- User for the object storage
  objectStorageAccessKeyId: "stub_user"
  # -- Password for access to object storage
  objectStorageSecretAccessKey: "stub_password"

## Docker image
image:
  registry: "gitregistry.knut.univention.de"
  repository: "univention/components/univention-portal/portal-listener"
  imagePullPolicy: "Always"
  tag: "latest"
  ## Define image sha256 as an alternative to `tag`
  # sha256:

  waitForDependency:
    registry: "gitregistry.knut.univention.de"
    repository: "univention/components/univention-portal/wait-for-dependency"
    imagePullPolicy: "Always"
    tag: "latest"
    ## Define image sha256 as an alternative to `tag`
    # sha256:

## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


# -- Deployment resources for the listener container
resources: {}
  # requests:
  #   memory: "512Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "4Gi"
  #   cpu: "4"

# -- Deployment resources for the dependency waiters
resourcesWaitForDependency: {}


autoscaling:
  enabled: false


persistence:
  data:
    storageClass: ""
    size: "1Gi"

...
