---
# Default values for univention-portal-listener
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []


# -- Application configuration of the Portal Listener
portal_listener:
  # Update configuration to mach the needs of the portal listener
  # -- Define LDAP Admin Group.
  # Example: `"cn=Domain Admins,cn=groups,dc=example,dc=com"`
  admin_group: null
  # -- Where to store the assets, e.g. portal entry icons
  assets_root: "http://portal-server:univention@portal-listener-store-dav/portal-assets/"
  # -- Define the authentication mode for the portal. Use "ucs" or "saml".
  auth_mode: "ucs"
  # -- Path to the CA certificate of the UCS machine.
  ca_cert_file: "/var/secrets/ca_cert"
  # -- Path to the certificate of the LDAP server
  cert_pem_file: "/var/secrets/cert_pem"
  # -- Internal domain name of the UCS machine
  domain_name: "univention.intranet"
  # -- Debug level of the listener
  debug_level: "5"
  # -- Defines if members of the Admin group can use the edit mode in the portal.
  editable: "true"
  # -- TODO: Clarify usage of this parameter
  environment: "production"

  # -- Base DN of the LDAP directory
  ldap_base_dn: null
  # -- Path to secret file for the bind to the LDAP directory
  ldap_bind_secret: "/var/secrets/ldap_secret"
  # -- Hostname of the LDAP server
  ldap_host: null
  # -- The IP address of the LDAP server.
  ldap_host_ip: null
  # -- DN of the UCS machine
  ldap_host_dn: null
  # -- Port to connect to the LDAP server.
  ldap_port: "389"
  # -- Configure if the LDAP client shall start TLS when connecting.
  # Chose from "never", "request" and "require".
  ldapStartTls: "never"
  # -- Allows to set the parameter "TLS_REQCERT" in the ldap client configuration.
  #
  # The man page of "ldap.conf" does provide details about the allowed values and how
  # this influences the client behavior.
  #
  # See: https://www.openldap.org/software//man.cgi?query=ldap.conf
  ldapTlsReqcert: "demand"

  # -- TODO: Clarify usage of this parameter
  log_level: "WARNING"
  # -- Path to the file which the machine secret
  machine_secret_file: "/var/secrets/machine_secret"
  # -- Hostname where the notifier can be reached.
  notifier_server: null
  # -- DN of the default portal
  portal_default_dn: null

  # -- UDM API connection URL
  udm_api_url: null
  udm_api_username: null
  udm_api_password_secret: "/var/secrets/machine_secret"

  # -- Define UCS internal endpoint.
  # Example: `"https://portal.example.com/univention/internal"`
  ucs_internal_url: "http://portal-listener:univention@portal-listener-store-dav/portal-data/"
  # -- Define UMC get endpoint.
  # Example: `"https://portal.example.com/univention/internal/umc/get"`
  umc_get_url: null
  # -- Define UMC session-info" endpoint.
  # Example: `"https://portal.example.com/univention/internal/umc/get/session-info"`
  umc_session_url: null


store-dav:
  bundled: true


## Docker image
image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/univention-portal/portal-listener"
  imagePullPolicy: "Always"
  tag: "latest"

  ## Define image sha256 as an alternative to `tag`
  # sha256:


## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1


## Deployment resources
resources:
  # requests:
  #   memory: "512Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "4Gi"
  #   cpu: "4"


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


autoscaling:
  enabled: false

...
