---
{{ include "common.configMap" (dict "top" . "overrides" "portal-listener.configMap") }}

{{- define "portal-listener.configMap" }}
{{- with .top }}
data:
  # TODO: listener specific environment configuration
  ENVIRONMENT: "{{ .Values.portal_listener.environment }}"
  LOG_LEVEL: "{{ .Values.portal_listener.log_level }}"
  PORTAL_SERVER_ADMIN_GROUP: {{ required "The parameter \"portal_listener.admin_group\" is required." .Values.portal_listener.admin_group | quote }}
  PORTAL_SERVER_AUTH_MODE: "{{ .Values.portal_listener.auth_mode }}"
  PORTAL_SERVER_EDITABLE: "{{ .Values.portal_listener.editable }}"
  PORTAL_SERVER_PORT: "{{ .Values.portal_listener.port }}"
  PORTAL_SERVER_UCS_INTERNAL_URL: {{ required "The parameter \"portal_listener.ucs_internal_url\" is required." .Values.portal_listener.ucs_internal_url | quote }}
  PORTAL_SERVER_UMC_GET_URL: {{ required "The parameter \"portal_listener.umc_get_url\" is required." .Values.portal_listener.umc_get_url | quote }}
  PORTAL_SERVER_UMC_SESSION_URL: {{ required "The parameter \"portal_listener.umc_session_url\" is required." .Values.portal_listener.umc_session_url | quote }}
  PORTAL_SERVER_AUTH_SECRET: {{ required "The parameter \"portal_listener.auth_secret\" is required." .Values.portal_listener.auth_secret | quote }}
{{- end }}
{{- end }}
