---
{{ include "common.configMap" (dict "top" . "overrides" "portal-listener.configMap") }}

{{- define "portal-listener.configMap" }}
{{- with .top }}
data:
  DOMAIN_NAME: "{{ .Values.portalListener.domainName }}"
  ENVIRONMENT: "{{ .Values.portalListener.environment }}"
  LDAP_BASE_DN: "{{ .Values.portalListener.ldapBaseDn }}"
  LDAP_PASSWORD: "{{ .Values.portalListener.ldapPassword }}"
  LDAP_PASSWORD_FILE: "{{ .Values.portalListener.ldapPasswordFile }}"
  LDAP_HOST: "{{ .Values.portalListener.ldapHost }}"
  LDAP_HOST_DN: "{{ .Values.portalListener.ldapHostDn }}"
  LDAP_PORT: "{{ .Values.portalListener.ldapPort }}"
  LOG_LEVEL: "{{ .Values.portalListener.logLevel }}"
  MACHINE_SECRET_FILE: "{{ .Values.portalListener.machineSecretFile }}"
  NOTIFIER_SERVER: "{{ .Values.portalListener.notifierServer }}"
  DEBUG_LEVEL: "{{ .Values.portalListener.debugLevel }}"
  PORTAL_DEFAULT_DN: "{{ .Values.portalListener.portalDefaultDn }}"
  PORTAL_LISTENER_LOG_STREAM: "true"
  PORTAL_SERVER_ADMIN_GROUP: {{ required "The parameter \"portalListener.adminGroup\" is required." .Values.portalListener.adminGroup | quote }}
  PORTAL_SERVER_ASSETS_ROOT: "{{ .Values.portalListener.assetsRoot }}"
  PORTAL_SERVER_AUTH_MODE: "{{ .Values.portalListener.authMode }}"
  PORTAL_SERVER_EDITABLE: "{{ .Values.portalListener.editable }}"
  PORTAL_SERVER_PORT: "{{ .Values.portalListener.port }}"
  PORTAL_SERVER_UCS_INTERNAL_URL: {{ required "The parameter \"portalListener.ucsInternalUrl\" is required." .Values.portalListener.ucsInternalUrl | quote }}
  PORTAL_SERVER_UMC_GET_URL: {{ required "The parameter \"portalListener.umcGetUrl\" is required." .Values.portalListener.umcGetUrl | quote }}
  PORTAL_SERVER_UMC_SESSION_URL: {{ required "The parameter \"portalListener.umcSessionUrl\" is required." .Values.portalListener.umcSessionUrl | quote }}
  PORTAL_UDM_API_URL: "{{ .Values.portalListener.udmApiUrl }}"
  PORTAL_UDM_API_USERNAME: "{{ .Values.portalListener.udmApiUsername }}"
  PORTAL_UDM_API_PASSWORD_FILE: "{{ .Values.portalListener.udmApiPasswordSecret }}"
  START_TLS: "{{ .Values.portalListener.ldapStartTls }}"
  TLS_REQCERT: "{{ .Values.portalListener.ldapTlsReqcert }}"
  CA_CERT_FILE: "{{ .Values.portalListener.caCertFile }}"
  CERT_PEM_FILE: "{{ .Values.portalListener.certPemFile }}"
  TLS_MODE: "{{ .tlsMode }}"
{{- end }}
{{- end }}
