apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.portal_listener.auth_ldap_secret | quote }}
  ca_cert: {{ .Values.portal_listener.ca_cert | quote }}
  cert_pem: {{ .Values.portal_listener.cert_pem | quote }}
  machine_secret: {{ .Values.portal_listener.machine_secret | quote }}
