apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.portalListener.ldapPassword | quote }}
  ca_cert: {{ .Values.portalListener.caCert | quote }}
  cert_pem: {{ .Values.portalListener.certPem | quote }}
  machine_secret: {{ .Values.portalListener.machineSecret | quote }}
