apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.portalListener.ldapPassword | quote }}
  caCert: {{ .Values.portalListener.caCert | quote }}
  certPem: {{ .Values.portalListener.certPem | quote }}
  machineSecret: {{ .Values.portalListener.machineSecret | quote }}
