---
{{ include "common.secret" (dict "top" . "overrides" "portal-listener.secret") }}

{{- define "portal-listener.secret" }}
{{- with .top }}
data:
  ldap_secret: {{ .Values.portalListener.ldapSecret | b64enc | quote }}
  ca_cert: {{ .Values.portalListener.caCert | quote }}
  cert_pem: {{ .Values.portalListener.certPem | quote }}
  machine_secret: {{ required "The parameter \"portalListener.machineSecret\" is required." .Values.portalListener.machineSecret | b64enc | quote }}
{{- end }}
{{- end }}
